### ISSUE TITLE
Check 

### ISSUE THREAD

**Issue by zeta96** [Dhruvgera/RockstarKernel_r4x#1]
dont forget to add CPU_INPUT_BOOST=y in defconfig, 

i wonder why do u use this commit https://github.com/Dhruvgera/RockstarKernel_r4x/commit/7516e517e11da31c751ae3b7921ad833a81e979f ,when booster and oc always on?

**Comment by Dhruvgera** [comment]
> dont forget to add CPU_INPUT_BOOST=y in defconfig,
> 
> i wonder why do u use this commit [7516e51](https://github.com/Dhruvgera/RockstarKernel_r4x/commit/7516e517e11da31c751ae3b7921ad833a81e979f) ,when booster and oc always on?

This commit ensures affinity of non critical threads onto the little cluster, whereas the CPU boost only acts for a short period of time, hence the commit is there. This also saves a lot of power, as assigning such tasks to the big cores leads to higher energy wastage, which is much more than what short periods of boosts take. 

As for OC, that is triggered only at high loads by EAS when the load capacity bypasses what is currently being used, and doing that is pretty essential as the chipset is quite old. As you might have seen, the big cores have very less overclock-ing, while the little cores have been boosted more, this is due to the above stated reason of saving power while ensuring better performance.
 
And yeah, will make sure to enable that :D
